# Generated by Django 4.0.1 on 2022-01-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Contato',
        ),
    ]
