# Generated by Django 4.0.1 on 2022-01-21 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_contatos_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
